# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farmer_name', models.CharField(max_length=30)),
                ('farmer_village', models.CharField(max_length=25)),
                ('farmer_farms', models.IntegerField()),
            ],
        ),
    ]
